version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: gym-mongo
    ports:
      - "27018:27017"
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - gym_data:/data/db

volumes:
  gym_data:
